# -*- coding: utf-8 -*-
"""D213_task2_PA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SMckrXYmNUgKad2XbiiLuXowVLccm7Tp
"""

# prompt: check  tensonflow version
!pip install tensorflow

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import pandas as pd
import numpy as np
import re
import seaborn as sns
import csv
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.optimizers import Adam

from google.colab import files
uploaded = files.upload()

df1 = pd.read_csv('amazon_cells_labelled.txt', sep='\t', header=None)

df2 = pd.read_csv('imdb_labelled.txt', sep='\t', header=None)

df3 = pd.read_csv('yelp_labelled.txt', sep='\t', header=None)

df = pd.concat([df1, df2, df3])

df.columns = ['review', 'sentiment']

display(df)

df.shape

df.head()

#countof postive  and negative  reviews
df.sentiment.value_counts()

import matplotlib.pyplot as plt
sns.countplot(x='sentiment', data=df)
plt.title('Sentiment Distribution')
plt.xlabel('Sentiment')
plt.ylabel('Count')

#count missing values
df.isna().sum()

#drop Na values
df.dropna(inplace=True)

#count missing values
df.isnull().sum()

"""#Part II: Data Preparation
B1. Perform exploratory data analysis on the chosen data set, and include an explanation of each of the following elements:


*   presence of unusual characters (e.g., emojis, non-English characters)
*   vocabulary size
*   proposed word embedding length
*  Statistical justification for the chosen maximum sequence length


"""

#identify and display all the unique characters present in the 'review'
list_of_chars = set(''.join(df['review'].astype(str)))
print(list(list_of_chars))

nltk.download('stopwords')
nltk.download('punkt_tab')
nltk.download('wordnet')
import re

#remove empty rows
df = df[df['review'].str.strip().astype(bool)]

#  As shown below there no emojis in the in data review dataset
emojis = [re.findall(r'[^\w\s,]', review) for review in df['review']]
print(emojis)

# as shown below there is no non englsih words in the data
non_english = [re.findall(r'[^\x00-\x7F]+', review) for review in df['review']]
print(non_english)

# Initialize stopwords
stop_words = set(stopwords.words('english'))

# Preprocessing function
def preprocess_text(description):
    # Remove punctuation but keep spaces
    description = re.sub("[^a-zA-Z\s]", "", description)
    # Convert to lowercase
    description = description.lower()
    # Perform tokenization
    description = nltk.word_tokenize(description)
    # Perform lemmatization
    lemma = nltk.WordNetLemmatizer()
    description = [lemma.lemmatize(word) for word in description]
    # Remove stopwords
    description = [word for word in description if word not in stop_words]
    return ' '.join(description)

# Apply preprocessing to all reviews
description_list = [preprocess_text(desc) for desc in df['review']]

# Tokenization and vectorization
vocab_size = 10000
tokenizer = Tokenizer(num_words=vocab_size, oov_token="<OOV>")
tokenizer.fit_on_texts(description_list)

# Convert texts to sequences
sequences = tokenizer.texts_to_sequences(description_list)

print("Sample tokenized sequence:", sequences[0])
print("Word index:", tokenizer.word_index)

"""B2.  Describe the goals of the tokenization process, including any code generated and packages that are used to normalize text during the tokenization process.

The goal of Tokenization to break raw text into smaller pieces, like words or subwords, making it easier to work with in machine learning. It standardizes the text by splitting it into tokens and handles out-of-vocabulary (OOV) words by assigning them a special token, like , so the model can deal with new or unseen words without issues. The text is then converted into sequences of integers, where each number represents a word's position in the vocabulary.
"""

# Vocabulary size
vocab_size = len(tokenizer.word_index) + 1
print("Vocabulary size:", vocab_size)

#demetmin the min max and  length of reviews
review_length = []
for char_length in df['review']:
  review_length.append(len(char_length))
  #print(review_length)

max_review_length = max(review_length)
min_review_length = min(review_length)
avg_review_length = sum(review_length)/len(review_length)
print("Max review length:",max_review_length)
print("Min review length:",min_review_length)
print("Avg review length:",avg_review_length)

#split the data into train and test
import numpy as np
from sklearn.model_selection import train_test_split


X = np.array(description_list)
y = df.sentiment.values

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=15, stratify=y)
y_train = pd.Series(y_train)
y_test = pd.Series(y_test)

print("X_train size:",X_train.shape)
print("X_tests size:",X_test.shape)
print("y_train size:",y_train.shape)
print("y_test size:",y_test.shape)

# Define max_length, padding_type, and trunc_type
max_length = int(np.percentile(review_length, 95))
padding_type = 'post'
trunc_type = 'post'

"""3B. Padding helps ensure all sequences in the dataset have the same length, making them suitable for input into neural network models like LSTMs, which require consistent input shapes. For this task, padding is used to extend shorter sequences to the desired length without changing their meaning, so the model can process the data effectively. Below is the padded result."""

#Apply Padding to training data
sequences_train = tokenizer.texts_to_sequences(X_train)
padded_train = pad_sequences(sequences_train, maxlen= max_length, padding =padding_type,truncating=trunc_type)
padded_train

#apply padding to test data
sequences_test = tokenizer.texts_to_sequences(X_test)
padded_test = pad_sequences(sequences_test, maxlen= max_length, padding =padding_type,truncating=trunc_type)
padded_test

"""4B.For this model, we use sigmoid activation in the output layer because it's perfect for binary classification tasks, like distinguishing between fake and genuine reviews, by producing outputs between 0 and 1. The binary_crossentropy loss function is chosen because it works well for binary classification, measuring the difference between predicted probabilities and the actual class labels. Adam is selected as the optimizer since it's efficient and adapts the learning rate, making it suitable for text classification tasks. We set num_epochs = 25 to allow the model enough time to learn without overfitting, while monitoring performance to adjust if needed."""

from sys import maxsize
#Display the padded sequence
np.set_printoptions(threshold=maxsize)
# Show first 50 tokens
print(padded_train[1][:50])

"""B5.  Explain the steps used to prepare the data for analysis, including the size of the training, validation, and test set split (based on the industry average).
To get the data ready for analysis, I first cleaned it up by removing any rows with missing values to ensure everything was complete and reliable. Then, I separated the text into X (the features) and the sentiment labels into y. After that, I split the data into 80% for training and 20% for testing, which is a common way to make sure the model gets enough data to learn while still having some set aside to check how well it performs on new, unseen data. I also made sure the split kept the balance between positive and negative sentiments, so the model gets a fair shot at learning from both. This setup ensures the process is straightforward and effective.
"""

#convert padded data to numpy array to be used in model
padded_train = np.array(padded_train)
padded_test = np.array(padded_test)
train_labels = np.array(y_train)
test_labels = np.array(y_test)

#B6.a copy of the prepared data set
#export the data to CSV file
pd.DataFrame(padded_train).to_csv('padded_train.csv', index=False)
pd.DataFrame(padded_test).to_csv('padded_test.csv', index=False)
pd.DataFrame(train_labels).to_csv('train_labels.csv', index=False)
pd.DataFrame(test_labels).to_csv('test_labels.csv', index=False)

from google.colab import files

files.download('padded_train.csv')
files.download('padded_test.csv')
files.download('train_labels.csv')
files.download('test_labels.csv')

"""
Part III: Network Architecture


C2.  Discuss the number of layers, the type of layers, and the total number of parameters.


*   The model starts with an Embedding layer to convert words into vectors, followed by a Bidirectional LSTM layer to capture context from both directions in a sequence. Dropout layers are included to prevent overfitting, and two Dense layers with ReLU activation refine the features. The final Dense layer uses a sigmoid activation to output probabilities for binary classification. Overall, the model has about 131,301 trainable parameters, carefully designed to balance performance and complexity.


C3 Justify the choice of hyperparameters, including the following elements:
• activation functions number of nodes per layer,loss function,optimizer,stopping criteria,evaluation metric  

*  The model uses ReLU activation for efficient learning and sigmoid for binary classification. The LSTM has 32 nodes, and the Dense layers (100 and 50 nodes) simplify feature extraction. Binary cross-entropy is the chosen loss function for accurate probability-based error calculation, and Adam optimizer ensures steady and efficient weight updates. Early stopping avoids overfitting by stopping training when validation loss stops improving, and accuracy is used as the evaluation metric to measure performance.



"""

#Building The Neural Network Model
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GlobalAveragePooling1D, Dense, Dropout
from tensorflow.keras.layers import LSTM, Bidirectional
from tensorflow.keras.regularizers import l2
vocab_size= 4757
embedding_dim = 32
max_length = 20
trunc_type='post'
padding_type='post'
oov_tok = "<OOV>"
activation = 'sigmoid'
loss = 'binary_crossentropy'
optimizer = Adam(learning_rate=0.0005)
num_epochs = 25
callback=tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3)

# Build the model

model = Sequential([
    Embedding(vocab_size, embedding_dim, input_length=max_length),
    Bidirectional(LSTM(32, dropout=0.2, recurrent_dropout=0.2)),
    Dropout(0.5),
    Dense(100, activation='relu', kernel_regularizer=l2(0.01)),
    Dropout(0.5),
    Dense(50, activation='relu'),
    Dense(1, activation='sigmoid')
])
 # Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# Build the model by providing input shape
model.build(input_shape=(None,max_length))
model.summary()

early_stopping_monitor = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss', patience=5, mode='min', restore_best_weights=True
)

history = model.fit(padded_train, train_labels, epochs=num_epochs, validation_data=(padded_test, test_labels), callbacks=[early_stopping_monitor])

"""model has moderate error when predicting outcomes on the test set with A loss of 0.49.The test accuracy shows that the model correctly predicted approximately 78% of the test labels."""

#verify model accuracy on test data
score = model.evaluate(padded_test, test_labels, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

import matplotlib.pyplot as plt
train_loss = history.history['loss']
val_loss = history.history['val_loss']
train_acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

plt.figure(figsize=(12, 4))
plt.plot(train_loss, label='Training Loss,', color = 'red')
plt.plot(val_loss, label='Validation Loss', color = 'blue')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.title('Training and Validation Loss')
plt.show()



"""Training and Validation Loss
The plot above shows that the training loss decreases steadily, indicating that the model is effectively learning and fitting the training data. Additionally, the decrease in validation loss suggests that the model generalizes well on unseen data.

"""

#plot accuracy
plt.figure(figsize=(12, 4))
plt.plot(train_acc, label='Training Accuracy', color = 'red')
plt.plot(val_acc, label='Validation Accuracy', color = 'blue')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

#perform model prediction
predictions = model.predict(padded_test)

i = 9
print("Review:", X_test[i], "\n")
print("Predicted:", "Fake" if predictions[i][0] >= 0.5 else "genuine", "reviews")
print("Actual:", "Fake" if test_labels[i] == 0 else "genuine", "reviews")

#Part IV: Model Evaluation



#E.Provide the code you used to save the trained network within the neural network.
model.save('my_model.keras')

from google.colab import files
files.download('my_model.keras')